#include "ext_types.h"
static DataTypeInfo rtDataTypeInfoTable [ ] = { { "real_T" , 0 , 8 } , {
"real32_T" , 1 , 4 } , { "int8_T" , 2 , 1 } , { "uint8_T" , 3 , 1 } , {
"int16_T" , 4 , 2 } , { "uint16_T" , 5 , 2 } , { "int32_T" , 6 , 4 } , {
"uint32_T" , 7 , 4 } , { "boolean_T" , 8 , 1 } , { "fcn_call_T" , 9 , 0 } , {
"int_T" , 10 , 4 } , { "pointer_T" , 11 , 8 } , { "action_T" , 12 , 8 } , {
"timer_uint32_pair_T" , 13 , 8 } , { "physical_connection" , 14 , 8 } , {
"int64_T" , 15 , 8 } , { "uint64_T" , 16 , 8 } , { "pointer_T" , 17 , 8 } , {
"FrmWksBus_2277297056879121903" , 18 , 24 } , { "string" , 19 , 8 } , {
"string" , 20 , 8 } , { "uint64_T" , 21 , 8 } , { "int64_T" , 22 , 8 } , {
"uint_T" , 23 , 32 } , { "char_T" , 24 , 8 } , { "uchar_T" , 25 , 8 } , {
"time_T" , 26 , 8 } } ; static uint_T rtDataTypeSizes [ ] = { sizeof ( real_T
) , sizeof ( real32_T ) , sizeof ( int8_T ) , sizeof ( uint8_T ) , sizeof ( int16_T ) , sizeof ( uint16_T ) , sizeof ( int32_T ) , sizeof ( uint32_T ) , sizeof ( boolean_T ) , sizeof ( fcn_call_T ) , sizeof ( int_T ) , sizeof ( pointer_T ) , sizeof ( action_T ) , 2 * sizeof ( uint32_T ) , sizeof ( int32_T ) , sizeof ( int64_T ) , sizeof ( uint64_T ) , sizeof ( pointer_T ) , sizeof ( FrmWksBus_2277297056879121903 ) , 8 , sizeof ( char_T ) , sizeof ( uint64_T ) , sizeof ( int64_T ) , sizeof ( uint_T ) , sizeof ( char_T ) , sizeof ( uchar_T ) , sizeof ( time_T ) } ; static const char_T * rtDataTypeNames [ ] = { "real_T" , "real32_T" , "int8_T" , "uint8_T" , "int16_T" , "uint16_T" , "int32_T" , "uint32_T" , "boolean_T" , "fcn_call_T" , "int_T" , "pointer_T" , "action_T" , "timer_uint32_pair_T" , "physical_connection" , "int64_T" , "uint64_T" , "pointer_T" , "FrmWksBus_2277297056879121903" , "string" , "string" , "uint64_T" , "int64_T" , "uint_T" , "char_T" , "uchar_T" , "time_T" } ; static DataTypeTransition rtBTransitions [ ] = { { ( char_T * ) ( & rtB . oubxqspwod ) , 0 , 0 , 50 } , { ( char_T * ) ( & rtB . eg2onjjxzy ) , 8 , 0 , 3 } , { ( char_T * ) ( & rtDW . ns3sryrqck [ 0 ] ) , 0 , 0 , 52 } , { ( char_T * ) ( & rtDW . gtoj3t1yxd . TimePtr ) , 11 , 0 , 25 } , { ( char_T * ) ( & rtDW . lweclmmpe0 ) , 6 , 0 , 9 } , { ( char_T * ) ( & rtDW . n0zxacxf1l . PrevIndex ) , 10 , 0 , 11 } , { ( char_T * ) ( & rtDW . gzroy3y1us ) , 8 , 0 , 5 } , { ( char_T * ) ( & rtDW . hyn34tqyhg [ 0 ] ) , 3 , 0 , 16 } , { ( char_T * ) ( & rtDW . pg5uo13xab ) , 8 , 0 , 4 } } ; static DataTypeTransitionTable rtBTransTable = { 9U , rtBTransitions } ; static DataTypeTransition rtPTransitions [ ] = { { ( char_T * ) ( & rtP . FrmWksBus_2277297056879121903_TU ) , 18 , 0 , 1 } , { ( char_T * ) ( & rtP . VSrc_eq_amp ) , 0 , 0 , 3 } , { ( char_T * ) ( & rtP . MonostableFlipFlop_x0 ) , 8 , 0 , 1 } , { ( char_T * ) ( & rtP . Constant_Value ) , 0 , 0 , 7 } , { ( char_T * ) ( & rtP . UnitDelay1_InitialCondition ) , 8 , 0 , 2 } } ; static DataTypeTransitionTable rtPTransTable = { 5U , rtPTransitions } ;
